#========================================
# Test profile settings (junit tests)
#========================================
logging:
  level:
    root: INFO

spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///junit-db
  jpa:
    ddl-auto: create-drop
    properties:
      hibernate:
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
  flyway:
    enabled: false
  sql:
    init:
      mode: never
  security:
    oauth2:
      common:
        token-url: token-url
        client-id: client-id
        client-secret: client-secret
      client:
        provider:
          agreement:
            token-uri: ${spring.security.oauth2.common.token-url}
          installedbase:
            token-uri: ${spring.security.oauth2.common.token-url}
          invoices:
            token-uri: ${spring.security.oauth2.common.token-url}
          measurement-data:
            token-uri: ${spring.security.oauth2.common.token-url}
        registration:
          agreement:
            client-id: ${spring.security.oauth2.common.client-id}
            client-secret: ${spring.security.oauth2.common.client-secret}
          installedbase:
            client-id: ${spring.security.oauth2.common.client-id}
            client-secret: ${spring.security.oauth2.common.client-secret}
          invoices:
            client-id: ${spring.security.oauth2.common.client-id}
            client-secret: ${spring.security.oauth2.common.client-secret}
          measurement-data:
            client-id: ${spring.security.oauth2.common.client-id}
            client-secret: ${spring.security.oauth2.common.client-secret}

integration:
  agreement:
    connect-timeout-in-seconds: 1
    read-timeout-in-seconds: 2
    url: agreement-integration-url
  installedbase:
    connect-timeout-in-seconds: 3
    read-timeout-in-seconds: 4
    url: installedbase-integration-url
  invoices:
    connect-timeout-in-seconds: 5
    read-timeout-in-seconds: 6
    url: invoices-integration-url
  measurement-data:
    connect-timeout-in-seconds: 7
    read-timeout-in-seconds: 8
    url: measurement-data-integration-url
  intric:
    connect-timeout-in-seconds: 9
    read-timeout-in-seconds: 10
    url: intric-integration-url
    oauth2:
      username: override
      password: override
      url: intric-token-url
