#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: self-service-ai
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        auto_quote_keyword: true
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none
  flyway:
    baseline-on-migrate: true
    enabled: false
  security:
    oauth2:
      client:
        registration:
          agreement:
            authorization-grant-type: client_credentials
            provider: agreement
          installedbase:
            authorization-grant-type: client_credentials
            provider: installedbase
          invoices:
            authorization-grant-type: client_credentials
            provider: invoices
          measurement-data:
            authorization-grant-type: client_credentials
            provider: measurement-data

integration:
  agreement:
    connect-timeout-in-seconds: 5
    read-timeout-in-seconds: 60
  installedbase:
    connect-timeout-in-seconds: 5
    read-timeout-in-seconds: 60
  invoices:
    connect-timeout-in-seconds: 5
    read-timeout-in-seconds: 60
  intric:
    connect-timeout-in-seconds: 5
    read-timeout-in-seconds: 60
  lime:
    connect-timeout-in-seconds: 5
    read-timeout-in-seconds: 60
  measurement-data:
    connect-timeout-in-seconds: 5
    read-timeout-in-seconds: 60
    
