#========================================
# Test profile settings (IT tests)
#========================================
logging:
  level:
    root: INFO

spring:
  security:
    oauth2:
      common:
        token-url: http://localhost:${wiremock.server.port}/wso2-token
        client-id: wso2-client-id
        client-secret: wso2-client-secret
      client:
        provider:
          agreement:
            token-uri: ${spring.security.ouauth2.common.token-url}
          installedbase:
            token-uri: ${spring.security.ouauth2.common.token-url}
          invoices:
            token-uri: ${spring.security.ouauth2.common.token-url}
          measurement-data:
            token-uri: ${spring.security.ouauth2.common.token-url}

        registration:
          agreement:
            client-id: ${spring.security.ouauth2.common.client-id}
            client-secret: ${spring.security.ouauth2.common.client-secret}
          installedbase:
            client-id: ${spring.security.ouauth2.common.client-id}
            client-secret: ${spring.security.ouauth2.common.client-secret}
          invoices:
            client-id: ${spring.security.ouauth2.common.client-id}
            client-secret: ${spring.security.ouauth2.common.client-secret}
          measurement-data:
            client-id: ${spring.security.ouauth2.common.client-id}
            client-secret: ${spring.security.ouauth2.common.client-secret}

integration:
  agreement:
    url: http://localhost:${wiremock.server.port}/agreement
  installedbase:
    url: http://localhost:${wiremock.server.port}/installedbase
  invoices:
    url: http://localhost:${wiremock.server.port}/invoices
  measurement-data:
    url: http://localhost:${wiremock.server.port}/measurementdata
  intric:
    url: http://localhost:${wiremock.server.port}/intric
    oauth2:
      username: intric-client-id
      password: intric-client-secret
      url: http://localhost:${wiremock.server.port}/intric/token
