---
x-generator: NSwag v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: Servanet.ItOps.ApiGatewayAdapter
  version: v1
servers:
- url: http://localhost:8080
paths:
  "/api/chathistorik/{sessionId}":
    get:
      tags:
      - Chathistorik
      summary: Hämta ett inlagg
      description: Hämta ett inlagg med hjälp av ett sessionId
      operationId: ApiEndpointsChathistorikHamtaChathistorikEndpoint
      parameters:
      - name: sessionId
        in: path
        required: true
        description: Id på inlägget som ska hämtas
        schema:
          type: string
      responses:
        '200':
          description: Loggen som postats in.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ServanetItOpsApiGatewayAdapterHttpContractsModelsResponsesChathistorikChathistorikResponse"
  "/api/chathistorik":
    post:
      tags:
      - Chathistorik
      summary: Skapa en chathistorik
      description: Skapa en ny chathistorik med meddelanden
      operationId: ApiEndpointsChathistorikSkapaChathistorikEndpoint
      requestBody:
        x-name: SkapaChathistorikRequest
        description: ''
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ServanetItOpsApiGatewayAdapterHttpContractsModelsRequestsChathistorikSkapaChathistorikRequest"
        required: true
        x-position: 1
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                "$ref": "#/components/schemas/FastEndpointsErrorResponse"
components:
  schemas:
    ServanetItOpsApiGatewayAdapterHttpContractsModelsResponsesChathistorikChathistorikResponse:
      type: object
      additionalProperties: false
      properties:
        chatSession:
          "$ref": "#/components/schemas/ServanetItOpsApiGatewayAdapterHttpContractsModelsRequestsChathistorikChatSessionDto"
    ServanetItOpsApiGatewayAdapterHttpContractsModelsRequestsChathistorikChatSessionDto:
      type: object
      additionalProperties: false
      properties:
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        name:
          type: string
        id:
          type: string
          format: guid
        messages:
          type: array
          items:
            "$ref": "#/components/schemas/ServanetItOpsApiGatewayAdapterHttpContractsModelsRequestsChathistorikMessageDto"
        feedback: {}
    ServanetItOpsApiGatewayAdapterHttpContractsModelsRequestsChathistorikMessageDto:
      type: object
      additionalProperties: false
      properties:
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        id:
          type: string
        question:
          type: string
        answer:
          type: string
        completion_model:
          "$ref": "#/components/schemas/ServanetItOpsApiGatewayAdapterHttpContractsModelsRequestsChathistorikCompletionModelDto"
        references: {}
        files: {}
        tools:
          "$ref": "#/components/schemas/ServanetItOpsApiGatewayAdapterHttpContractsModelsRequestsChathistorikToolsDto"
    ServanetItOpsApiGatewayAdapterHttpContractsModelsRequestsChathistorikCompletionModelDto:
      type: object
      additionalProperties: false
      properties:
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        id:
          type: string
        name:
          type: string
        nickname:
          type: string
        family:
          type: string
        token_limit:
          type: integer
          format: int32
        is_deprecated:
          type: boolean
        nr_billion_parameters: {}
        hf_link: {}
        stability:
          type: string
        hosting:
          type: string
        open_source: {}
        description:
          type: string
        deployment_name:
          type: string
        org:
          type: string
        vision:
          type: boolean
        is_org_enabled:
          type: boolean
        is_org_default:
          type: boolean
    ServanetItOpsApiGatewayAdapterHttpContractsModelsRequestsChathistorikToolsDto:
      type: object
      additionalProperties: false
      properties:
        assistants: {}
    FastEndpointsErrorResponse:
      type: object
      additionalProperties: false
      properties:
        statusCode:
          type: integer
          format: int32
          default: 400
        message:
          type: string
          default: One or more errors occurred!
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
    ServanetItOpsApiGatewayAdapterHttpContractsModelsRequestsChathistorikSkapaChathistorikRequest:
      type: object
      additionalProperties: false
      required:
      - chatSession
      properties:
        chatSession:
          minLength: 1
          nullable: false
          "$ref": "#/components/schemas/ServanetItOpsApiGatewayAdapterHttpContractsModelsRequestsChathistorikChatSessionDto"
        kundnummer:
          type: string
        identitetsnummer:
          type: string
        isOrganisation:
          type: boolean
  securitySchemes:
    JWTBearerAuth:
      type: http
      description: Enter a JWT token to authorize the requests...
      scheme: Bearer
      bearerFormat: JWT
    X-Client-Secret:
      type: apiKey
      description: Ange din X-Client-Secret i detta fält.
      name: X-Client-Secret
      in: header
security:
- X-Client-Secret: []
